sudo: required
services:
  - docker

before_install:
  - docker build -t erenlevi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true erenlevi/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ap-south-1-738044013432"
  bucket_path: "Docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
